-- CreatorFlow - PostgreSQL 15+
-- 01_schema.sql
-- C# WinForms + .NET 10 + Npgsql
-- Run this file on an empty database named creatorflow.

BEGIN;

CREATE TYPE account_status AS ENUM ('ACTIVE','LOCKED','DISABLED');
CREATE TYPE project_status AS ENUM ('ACTIVE','ARCHIVED');
CREATE TYPE project_role AS ENUM ('OWNER','MANAGER','CREATOR');
CREATE TYPE invitation_status AS ENUM ('PENDING','ACCEPTED','REJECTED','EXPIRED','CANCELLED');
CREATE TYPE idea_status AS ENUM ('DRAFT','BACKLOG','CONVERTED','ARCHIVED');
CREATE TYPE content_priority AS ENUM ('LOW','MEDIUM','HIGH','URGENT');
CREATE TYPE content_status AS ENUM ('IDEA','SCRIPT','PRODUCTION','EDITING','REVIEW','READY','PUBLISHED','ARCHIVED');
CREATE TYPE publication_status AS ENUM ('PLANNED','READY','PUBLISHED','FAILED');
CREATE TYPE assignment_status AS ENUM ('ASSIGNED','IN_PROGRESS','COMPLETED','CANCELLED');
CREATE TYPE review_status AS ENUM ('PENDING','APPROVED','REJECTED');
CREATE TYPE relation_type AS ENUM ('REPURPOSED','VARIANT');
CREATE TYPE notification_type AS ENUM (
  'ASSIGNMENT','REVIEW_SUBMITTED','REVIEW_APPROVED','REVIEW_REJECTED',
  'FEEDBACK','STATUS_CHANGED','DEADLINE_NEAR','OVERDUE','INVITATION','SYSTEM'
);
CREATE TYPE subscription_status AS ENUM ('ACTIVE','EXPIRED','CANCELLED');
CREATE TYPE report_status AS ENUM ('OPEN','IN_REVIEW','RESOLVED','REJECTED');
CREATE TYPE ai_request_status AS ENUM ('PENDING','SUCCESS','FAILED');
CREATE TYPE ai_request_type AS ENUM ('IDEA','TITLE','OUTLINE','SCRIPT','REPURPOSE','PERFORMANCE_ANALYSIS','OTHER');

CREATE TABLE users (
 user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email VARCHAR(255) NOT NULL,
 password_hash TEXT NOT NULL,
 display_name VARCHAR(150) NOT NULL,
 avatar_url TEXT,
 account_status account_status NOT NULL DEFAULT 'ACTIVE',
 is_system_admin BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 last_login_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_users_email_lower ON users(LOWER(email));

CREATE TABLE plans (
 plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(50) NOT NULL UNIQUE,
 name VARCHAR(100) NOT NULL,
 description TEXT,
 price_monthly NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK(price_monthly>=0),
 max_projects INTEGER CHECK(max_projects IS NULL OR max_projects>=0),
 max_members INTEGER CHECK(max_members IS NULL OR max_members>=0),
 ai_request_limit INTEGER CHECK(ai_request_limit IS NULL OR ai_request_limit>=0),
 is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE subscriptions (
 subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 plan_id BIGINT NOT NULL REFERENCES plans(plan_id) ON DELETE RESTRICT,
 status subscription_status NOT NULL DEFAULT 'ACTIVE',
 started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 expires_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CHECK(expires_at IS NULL OR expires_at > started_at)
);

CREATE TABLE reports (
 report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 reporter_user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
 reported_user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
 reason TEXT NOT NULL,
 details TEXT,
 status report_status NOT NULL DEFAULT 'OPEN',
 handled_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
 handled_note TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 handled_at TIMESTAMPTZ
);

CREATE TABLE audit_logs (
 audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 actor_user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
 action VARCHAR(100) NOT NULL,
 entity_type VARCHAR(80),
 entity_id BIGINT,
 description TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE projects (
 project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_name VARCHAR(200) NOT NULL,
 description TEXT,
 owner_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 status project_status NOT NULL DEFAULT 'ACTIVE',
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE project_members (
 project_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
 user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 role project_role NOT NULL,
 joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 is_active BOOLEAN NOT NULL DEFAULT TRUE,
 UNIQUE(project_id,user_id)
);

CREATE TABLE project_invitations (
 invitation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
 invited_email VARCHAR(255) NOT NULL,
 invited_user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
 invited_by BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 role project_role NOT NULL CHECK(role <> 'OWNER'),
 token VARCHAR(200) NOT NULL UNIQUE,
 status invitation_status NOT NULL DEFAULT 'PENDING',
 expires_at TIMESTAMPTZ NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 responded_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_pending_invitation
ON project_invitations(project_id,LOWER(invited_email))
WHERE status='PENDING';

CREATE TABLE ideas (
 idea_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
 title VARCHAR(250) NOT NULL,
 description TEXT,
 status idea_status NOT NULL DEFAULT 'DRAFT',
 created_by BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contents (
 content_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
 source_idea_id BIGINT REFERENCES ideas(idea_id) ON DELETE SET NULL,
 title VARCHAR(250) NOT NULL,
 description TEXT,
 script TEXT,
 content_type VARCHAR(100),
 priority content_priority NOT NULL DEFAULT 'MEDIUM',
 status content_status NOT NULL DEFAULT 'IDEA',
 deadline TIMESTAMPTZ,
 planned_publish_at TIMESTAMPTZ,
 created_by BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE platforms (
 platform_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(50) NOT NULL UNIQUE,
 name VARCHAR(100) NOT NULL UNIQUE,
 is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE content_platforms (
 content_platform_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 content_id BIGINT NOT NULL REFERENCES contents(content_id) ON DELETE CASCADE,
 platform_id BIGINT NOT NULL REFERENCES platforms(platform_id) ON DELETE RESTRICT,
 publication_status publication_status NOT NULL DEFAULT 'PLANNED',
 post_url TEXT,
 planned_publish_at TIMESTAMPTZ,
 published_at TIMESTAMPTZ,
 UNIQUE(content_id,platform_id)
);

CREATE TABLE tags (
 tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
 name VARCHAR(80) NOT NULL,
 UNIQUE(project_id,name)
);

CREATE TABLE content_tags (
 content_id BIGINT NOT NULL REFERENCES contents(content_id) ON DELETE CASCADE,
 tag_id BIGINT NOT NULL REFERENCES tags(tag_id) ON DELETE CASCADE,
 PRIMARY KEY(content_id,tag_id)
);

CREATE TABLE content_attachments (
 attachment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 content_id BIGINT NOT NULL REFERENCES contents(content_id) ON DELETE CASCADE,
 display_name VARCHAR(255) NOT NULL,
 attachment_type VARCHAR(50) NOT NULL DEFAULT 'LINK',
 resource_url TEXT NOT NULL,
 added_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE content_relations (
 relation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_content_id BIGINT NOT NULL REFERENCES contents(content_id) ON DELETE CASCADE,
 derived_content_id BIGINT NOT NULL REFERENCES contents(content_id) ON DELETE CASCADE,
 relation_type relation_type NOT NULL DEFAULT 'REPURPOSED',
 created_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(source_content_id,derived_content_id),
 CHECK(source_content_id<>derived_content_id)
);

CREATE TABLE content_assignments (
 assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 content_id BIGINT NOT NULL REFERENCES contents(content_id) ON DELETE CASCADE,
 assignee_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 assigned_by BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 status assignment_status NOT NULL DEFAULT 'ASSIGNED',
 progress_percent SMALLINT NOT NULL DEFAULT 0 CHECK(progress_percent BETWEEN 0 AND 100),
 deadline TIMESTAMPTZ,
 assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 completed_at TIMESTAMPTZ
);

CREATE TABLE content_status_history (
 history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 content_id BIGINT NOT NULL REFERENCES contents(content_id) ON DELETE CASCADE,
 from_status content_status,
 to_status content_status NOT NULL,
 changed_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
 note TEXT,
 changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reviews (
 review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 content_id BIGINT NOT NULL REFERENCES contents(content_id) ON DELETE CASCADE,
 review_no INTEGER NOT NULL CHECK(review_no>0),
 submitted_by BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 reviewer_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
 status review_status NOT NULL DEFAULT 'PENDING',
 feedback TEXT,
 reviewed_at TIMESTAMPTZ,
 UNIQUE(content_id,review_no)
);

CREATE TABLE notifications (
 notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 recipient_user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 project_id BIGINT REFERENCES projects(project_id) ON DELETE CASCADE,
 content_id BIGINT REFERENCES contents(content_id) ON DELETE CASCADE,
 type notification_type NOT NULL,
 title VARCHAR(200) NOT NULL,
 message TEXT NOT NULL,
 is_read BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 read_at TIMESTAMPTZ,
 CHECK(
   (is_read=FALSE AND read_at IS NULL)
   OR
   (is_read=TRUE AND read_at IS NOT NULL)
 )
);

CREATE TABLE content_metrics (
 metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 content_platform_id BIGINT NOT NULL REFERENCES content_platforms(content_platform_id) ON DELETE CASCADE,
 views BIGINT NOT NULL DEFAULT 0 CHECK(views>=0),
 likes BIGINT NOT NULL DEFAULT 0 CHECK(likes>=0),
 comments BIGINT NOT NULL DEFAULT 0 CHECK(comments>=0),
 shares BIGINT NOT NULL DEFAULT 0 CHECK(shares>=0),
 recorded_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
 recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ai_requests (
    ai_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 project_id BIGINT REFERENCES projects(project_id) ON DELETE CASCADE,
 idea_id BIGINT REFERENCES ideas(idea_id) ON DELETE SET NULL,
 content_id BIGINT REFERENCES contents(content_id) ON DELETE SET NULL,
 request_type ai_request_type NOT NULL,
 prompt_text TEXT,
 response_text TEXT,
 model_name VARCHAR(100),
 status ai_request_status NOT NULL DEFAULT 'PENDING',
 input_tokens INTEGER CHECK(input_tokens IS NULL OR input_tokens>=0),
 output_tokens INTEGER CHECK(output_tokens IS NULL OR output_tokens>=0),
 estimated_cost NUMERIC(12,6) CHECK(estimated_cost IS NULL OR estimated_cost>=0),
 error_message TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 completed_at TIMESTAMPTZ
);

CREATE INDEX ix_projects_owner ON projects(owner_id);
CREATE INDEX ix_project_members_user ON project_members(user_id,is_active);
CREATE INDEX ix_ideas_project_status ON ideas(project_id,status);
CREATE INDEX ix_contents_project_status ON contents(project_id,status);
CREATE INDEX ix_contents_deadline ON contents(deadline);
CREATE INDEX ix_assignments_assignee_status ON content_assignments(assignee_id,status);
CREATE INDEX ix_status_history_content_time ON content_status_history(content_id,changed_at DESC);
CREATE INDEX ix_reviews_content_status ON reviews(content_id,status);
CREATE INDEX ix_notifications_recipient_read ON notifications(recipient_user_id,is_read,created_at DESC);
CREATE INDEX ix_metrics_platform_time ON content_metrics(content_platform_id,recorded_at DESC);
CREATE INDEX ix_ai_requests_user_time ON ai_requests(user_id,created_at DESC);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at=CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_projects_updated_at
BEFORE UPDATE ON projects
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_ideas_updated_at
BEFORE UPDATE ON ideas
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_contents_updated_at
BEFORE UPDATE ON contents
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;

-- Business rules handled in Service:
-- Owner must also exist in project_members with role OWNER.
-- Workflow: IDEA -> SCRIPT -> PRODUCTION -> EDITING -> REVIEW -> READY -> PUBLISHED.
-- Reject REVIEW -> EDITING; resubmit creates a new review row.
-- Only OWNER/MANAGER can assign/review.
-- Assignee must belong to the same Project.
-- Actual publish time is stored per platform in content_platforms.published_at.
-- Never store plaintext passwords.
