<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>CreatorFlow.Api-SCRUM-78</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CreatorFlow.Contracts\CreatorFlow.Contracts.csproj" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>
</Project>
